sudo: false
language: cpp
compiler:
  - gcc
  - clang

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "PY2nEbgPiLlKzs5bojGmDE1KFjTQws504ZoEBh3O9AAJWfkEMQvhwfkO6wfp3hYXsQ4fZUfJM03CsJFxXiGk1oxXqBQ/lB1eKhf7GN8AY2giD+Ei6dD3hKbUwlmsbCk1YXryWsffrGwY/++0sRkgcYqAKHvQ1Z5POTNHNGMcg9M="
   - coverity_scan_run_condition='"$CC" = gcc'
   - coverity_scan_script_test_mode=false

script:
  - if [ "$COVERITY_SCAN_BRANCH" != 1 ]; then ./autogen.sh; fi
  - if [ "$COVERITY_SCAN_BRANCH" != 1 ]; then ./configure || cat config.log; fi
  - if [ "$COVERITY_SCAN_BRANCH" != 1 ]; then make -j4; fi

addons:
  apt:
    packages:
      - libxml2-dev
  coverity_scan:
    build_script_url: https://raw.githubusercontent.com/$TRAVIS_REPO_SLUG/$TRAVIS_BRANCH/.travis_coverity.sh
    project:
      name: $TRAVIS_REPO_SLUG
    notification_email: drmccoy@drmccoy.de
    build_command_prepend: "./autogen.sh && ./configure"
    build_command: "make -j4"
    branch_pattern: coverity_scan

notifications:
  email:
    recipients:
      - ndbrandes@gmail.com
    on_success: change
    on_failure: always
  irc:
    channels:
      - "chat.freenode.net#xoreos"
    on_success: change
    on_failure: always
    use_notice: true
